### ISSUE TITLE
Pyhidra Plugin not appearing

### ISSUE THREAD

**Issue by bpengu1n** [dod-cyber-crime-center/pyhidra#19]
### Running: 
   Ghidra 10.1.5 (self-compiled; JRE 17.0.4)
   Ubuntu 22.04

### To Reproduce:
1) Installed pyhidra: ```pip install pyhidra```
2) Ran pyhidraw: ``` ./pyhidraw ```
3) Within Ghidra, navigated to File > Configure, then clicked "configure" under Experimental
4) Observed Pyhidraw was not in the list of available experimental extensions.

### Extensions directory tree:
```bash
~/.ghidra/.ghidra_10.1.5_DEV/Extensions$ tree -s pyhidra/
[       4096]  pyhidra/
├── [        306]  extension.properties
├── [       4096]  lib
│   └── [      24015]  pyhidra.jar
└── [          0]  Module.manifest

1 directory, 3 files
```

**Comment by dc3-tsd** [comment]
Please run the following script as follows, open the Code Browser, confirm that the plugin is not present in the Experimental section of the configure menu, close Ghidra and attach the resulting log file.

This script changes the Java logging level to log everything and the contents of the log will be extremely verbose.
Any stack traces present in the log might not indicate a problem.
The debug.log4j.xml file may be deleted afterwards.

`python main.py > pyhidra.log 2>&1`

```python
import re
from pyhidra.constants import GHIDRA_INSTALL_DIR
from pyhidra.launcher import GuiPyhidraLauncher

LOG_CONFIG_FILE = 'debug.log4j.xml'
LOG_LEVEL_PATTERN = re.compile(r'(.*)level="\S+"/>')


def create_log_config():
    config_path = GHIDRA_INSTALL_DIR / 'support' / LOG_CONFIG_FILE
    with open(LOG_CONFIG_FILE, 'w+', encoding='utf-8') as fp:
        for line in config_path.read_text().splitlines():
            match = LOG_LEVEL_PATTERN.match(line)
            if match:
                fp.write(match.group(1))
                fp.write('level="ALL"/>')
            else:
                fp.write(line)
            fp.write('\n')


if __name__ == '__main__':
    create_log_config()
    launcher = GuiPyhidraLauncher(True)
    launcher.add_vmargs('-Dlog4j.configurationFile='+LOG_CONFIG_FILE)
    launcher.start()

```

**Comment by dc3-tsd** [comment]
Please let us know if you are still experiencing this issue.  If we do not hear back before 2022-09-09 this issue with be closed.

**Comment by Decap1tator** [comment]
I'm having this issue as well with Ghidra 11.3.2 and pyhidra 1.3.0. When I attempt to run the above script I get 
```python
ModuleNotFoundError: No module named 'pyhidra.constants'
```

pyhidra shows up on the `file -> Install Extensions` but it does not show up when I click on `Configure` under `Experimental`

**Comment by Decap1tator** [comment]
Figured it out. pyhidra doesn't show up in the project browser. but it shows up properly in the code browser. It might be helpful to update the instructions to advise that you can't open the codebrowser until you create a project.
