### ISSUE TITLE
askChoices error python3.11

### ISSUE THREAD

**Issue by moval0x1** [dod-cyber-crime-center/pyhidra#27]
Hi, I'm trying to use askChoices with Pyhidra (python 3.11), but I always receive an error:

```
Tests.py> Running...
Tests.py> Traceback (most recent call last):
  File "/home/remnux/ghidra_scripts/Tests.py", line 51, in <module>
    choices = askChoices("Options", "Select your option",
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: No matching overloads found for ghidra.app.script.GhidraScript.askChoices(str,str,list,list), options are:
	public java.util.List ghidra.app.script.GhidraScript.askChoices(java.lang.String,java.lang.String,java.util.List) throws ghidra.util.exception.CancelledException
	public java.util.List ghidra.app.script.GhidraScript.askChoices(java.lang.String,java.lang.String,java.util.List,java.util.List) throws ghidra.util.exception.CancelledException



Tests.py> Finished!
```

Code:
```
choices = askChoices("Options", "Select your option",
                     [0, 1, 2],
                     ["Option 1", "Option 2", "Option 3"])
```

The same code without Pyhidra (with python 2.7) runs correctly.
![image](https://github.com/dod-cyber-crime-center/pyhidra/assets/6342021/b548364e-b1a9-48b2-a1ff-35b907af33fa)

Just askChoice(s) has this problem, askInt, askString, askDouble all these work well. Can someone please help me with this issue?
![image](https://github.com/dod-cyber-crime-center/pyhidra/assets/6342021/91281b5a-30e5-4e19-ae11-b752766cc138)

**Comment by dc3-tsd** [comment]
For lists being passed into Java functions, you'll need to first convert the list from Python  to Java using something like java.util.ArrayList​ so Java can figure out the correct overloaded method to call.  We are looking into improving this so that lists will automatically convert in the background when possible.


```python

choices = askChoices(
    "Options", "Select your option",
    java.util.ArrayList([0, 1, 2]),
    java.util.ArrayList(["Option 1", "Option 2", "Option 3"]),
)
```

**Comment by moval0x1** [comment]
Thank you, @dc3-tsd! It worked perfectly!
